### PR TITLE
New single-letter test: constant -> constant+

### PR DESCRIPTION
**Pull request by dwyafon**

### CODE REVIEW

**Comment by dwyafon** [comment]
Added test for row 3 of TPP: constant -> constant+

Specifically: test with a multi-character string input

I've updated lib/mumble.js to allow for the first two tests to pass and the third test to fail -- is this a helpful (correct?) way to ping-pong it back to you?

**Comment by zackads** [comment]
> I've updated lib/mumble.js to allow for the first two tests to pass and the third test to fail -- is this a helpful (correct?) way to ping-pong it back to you?

It certainly is!  Though you wouldn't 'normally' commit code with a failing test, while doing asynchronous pairing like this it's totally OK (and the only way it can be done to be fair 😂).

A few questions / feedback points on this PR:
- We've gone from testing `mumble("Z") => "Z"` to `mumble("YTREWQ") => ...`.  Are you sure we've fully tested the first behaviour and are ready to move on? (Clue: what's the simplest test you could write that would cause me to have to remove the constant at line 6 of the lib file?)
- If you're confident `"YTREWQ"` is the next test case, double check the assertion at line 18 of the test file.  Does the test expect what the `mumble` method is supposed to do?
- If you're still confident `"YTREWQ"` is definitely the next test case (😉), please commit it to a new feature branch as it doesn't belong in `single_letter`.

Hope this makes sense!  Happy to do a short call to help with any of the above 😊

**Comment by dwyafon** [comment]
Another way to test the function at the single-letter stage is to test with a lower-case 'z' -- is this what you're thinking? It would require a change in the form of the single-character constant (but I'm wondering if you're thinking about having to remove the constant as the return value regardless of form) . . .

**Comment by zackads** [comment]
> Another way to test the function at the single-letter stage is to test with a lower-case 'z' -- is this what you're thinking? It would require a change in the form of the single-character constant (but I'm wondering if you're thinking about having to remove the constant as the return value regardless of form) . . .

Personally I'd just go with a different uppercase character.  

With the code as it is, the transformation we need to do to go from `"A" => "A"` to `"Z" => "Z"` is lower down on the TPP than to go from `"A" => "A"` to `"a" => "A"`.  The former is constant => scalar, the second is constant => statement (convert to uppercase using a built-in method) 

This will feel like nitpicking (it did when it was first drilled in to me!) but spend a little bit of time getting in the swing of this it'll a) become rapid and second nature, and b) save some pitfalls when TDDing and you try and reach too far with one transformation.

**Comment by dwyafon** [comment]
I'm wondering how long it's necessary to stay with a particular level of transformation before moving to the next one on the list.

If testing with an empty string is Nil -> constant, and testing with 'Z' is constant -> constant+, then by testing with 'YTREWQ' is that staying on the constant -> constant+ transformation (with the use of an increasingly complex constant)?

On page 44, Santos writes : 'Write another failing test and (ideally) stay on the same transformation or, if required, move to the next one on the table.' I ask: What are the benefits of staying on the same transformation (e.g., of testing with a different uppercase letter)? Maybe, I'm beginning to wonder, there are opportunities to learn about the code by going through the red-green process as many times as possible on the same level of transformation -- that by testing with a different, single uppercase letter in mumbles, and thus achieve a failing test, we can then better understand how to transform the function to enable it to work successfully with any single, uppercase letter.

As well, I'm wondering if the use of if/else in lib/mumble.js to allow the first test to pass has meant jumping too far (and too soon) down the TPP list . . .

**Pull request merged**
